### ISSUE TITLE
crn = skid

### ISSUE THREAD

**Issue by ElieLeHackeur** [billythegoat356/discord#5]
- CRN#3956 | Le plus gros skid de la terre, fait trop le mec par mess et en voc, se proclame certified dev mais ne sait meme pas installer un module python, insulte tout le monde, méga hautain, clc... Bref ce mec est une merde humaine

**Comment by matxd291** [comment]
Je confirme ce qu'il dit

**Comment by ElieLeHackeur** [comment]
🖕

**Comment by matxd291** [comment]
> 🖕

Je rigolais bebou
